name: Issue Helper

on:
  issues:
    types: [opened, labeled]

# 权限配置
permissions:
  issues: write

jobs:
  issue-handler:
    runs-on: ubuntu-latest
    steps:
      # 自动欢迎
      - name: Welcome Comment
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            👋 您好 @${{ github.event.issue.user.login }}，感谢提交 Issue！
            🚀 我们已经收到您的反馈，会尽快确认你的问题

            在等待回复期间，您可以：
              - 📖 查看 [项目文档](https://github.com/imsyy/SPlayer/blob/dev/README.md)
              - 🔍 搜索 [现有 Issues](https://github.com/imsyy/SPlayer/issues) 查看是否有类似问题
      # 自动关闭
      - name: Auto Close
        if: github.event.action == 'labeled' && contains(fromJSON('["不会修复", "无效", "重复"]'), github.event.label.name)
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment, close-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            抱歉，由于被标记为 **${{ github.event.label.name }}**，该 Issue 将自动关闭
            如果您认为该 Issue 仍然有效，请创建新的 Issue，我们会尽快确认并修复
      # 有问题回复
      - name: Auto Reply
        if: github.event.action == 'labeled' && github.event.label.name == '有问题'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🤝 您好 @${{ github.event.issue.user.login }}，感谢您的反馈！
            由于缺少复现步骤，我们无法重现问题，因此无法修复
            请确保您已经详细描述了问题的复现步骤，维护团队会尽快查看
      # 已确认 BUG
      - name: Auto Confirm BUG
        if: github.event.action == 'labeled' && github.event.label.name == 'BUG'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "remove-labels, create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "有问题, 过期"
          body: |
            🤝 您好 @${{ github.event.issue.user.login }}，感谢您的反馈！我们已经确认该问题，并将在下一个版本中修复
      # 无法复现
      - name: Auto Unreproducible
        if: github.event.action == 'labeled' && github.event.label.name == '无法复现'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🤝 您好 @${{ github.event.issue.user.login }}，感谢您的反馈！
            由于无法复现问题，我们无法修复
            请确保您已经详细描述了问题的复现步骤，维护团队会尽快查看
      # 已修复
      - name: Auto Fixed
        if: github.event.action == 'labeled' && github.event.label.name == '已修复'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment, remove-labels, close-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "BUG"
          close-reason: "completed"
          body: |
            🎉 您好 @${{ github.event.issue.user.login }}，感谢您的反馈！
            该问题已在当前开发版或下一个正式版中修复完成。
            若您觉得仍存在问题，请创建新的 Issue，我们会尽快确认并修复
